export default {
  headless: false,
  ignoreHTTPSErrors: true,
  args: [
    '--disable-gpu',
    '--disable-cloud-import',
    '--disable-gesture-typing',
    '--disable-infobars',
    '--disable-notifications',
    '--disable-offer-store-unmasked-wallet-cards',
    '--disable-offer-upload-credit-cards',
    '--disable-print-preview',
    '--disable-speech-api',
    '--disable-tab-for-desktop-share',
    '--disable-translate',
    '--disable-voice-input',
    '--disable-wake-on-wifi',
    '--enable-async-dns',
    '--enable-simple-cache-backend',
    '--enable-tcp-fast-open',
    '--hide-scrollbars',
    '--mute-audio',
    '--no-default-browser-check',
    '--no-pings',
    '--no-zygote',
    '--prerender-from-omnibox=disabled',
    '--use-gl=swiftshader',
    '--no-sandbox',
    '--disable-web-security',
    '--font-render-hinting=none',
    '--enable-font-antialiasing',
    '--single-process',
    '--memory-pressure-off',
    '--no-sandbox',
    '--disable-setuid-sandbox'
  ]
};